query Publications($search: String, $filters: FilterInput, $after: String) {
  publications(search: $search, filters: $filters, after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }

    edges {
      cursor
      node {
        id
        abstract
        authors {
          firstName
          lastName
        }
        created
        disciplines {
          value
        }
        fileAttached
        id
        keywords {
          value
        }
        slug
        journal {
          value
        }
        title
        websites
        year {
          value
        }
      }
    }
  }
}
