query Publication($slug: String!) {
  publication: publicationBySlug(slug: $slug) {
    abstract
    authors {
      firstName
      lastName
    }
    created
    disciplines {
      value
    }
    fileAttached
    id
    keywords {
      value
    }
    slug
    journal {
      value
    }
    title
    websites
    year {
      value
    }
    recommendations(first: 5) {
      score
      publication {
        abstract
        authors {
          firstName
          lastName
        }
        created
        disciplines {
          value
        }
        fileAttached
        id
        keywords {
          value
        }
        slug
        journal {
          value
        }
        title
        websites
        year {
          value
        }
      }
    }
  }
}
