query Queue($channel: String!, $first: Int, $search: String) {
  queue(channel: $channel) {
    id
    slug
    title
  }

  publicationsByTitle(first: $first, title: $search) {
    id
    slug
    created
    title
    hasBeenPosted(channel: $channel)
  }
}
