query Queue($channel: String!, $first: Int, $search: String) {
  queue(channel: $channel) {
    id
    slug
    title
  }

  publications(first: $first, search: $search) {
    edges {
      cursor
      node {
        id
        slug
        created
        title
        hasBeenPosted(channel: $channel)
      }
    }
  }
}
