query Search($term: String!) {
  fieldSuggestions(search: $term, first: 5) {
    value {
      __typename
      ... on Year {
        year: value
        publicationCount
      }
      ... on Author {
        firstName
        lastName
        publicationCount
      }
      ... on Journal {
        value
        publicationCount
      }
      ... on Discipline {
        value
        publicationCount
      }
      ... on Keyword {
        value
        publicationCount
      }
    }
    field
    score
  }

  publications(search: $term, first: 3) {
    edges {
      node {
        id
        title
        slug
      }
    }
  }
}
