name: Client Unit Tests

on: ['push']

env:
  COVERALLS_REPO_TOKEN: '${{ secrets.COVERALLS_REPO_TOKEN }}'
  COVERALLS_GIT_BRANCH: '${{ github.ref }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd client install --frozen-lockfile

      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd client build

      - name: yarn lint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd client lint

      - name: yarn test:unit
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd client test:unit --ci

      - name: yarn coveralls
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd client coveralls
